"use strict";

const path = require("path");
const { assertNodeSyntaxFile, assertSourceIncludesFile } = require("../../../../test-support/module-contract-helper.js");

const TARGET_REL = "scripts/deploy-production.js";
const TARGET_PATH = path.join(process.cwd(), TARGET_REL);
assertNodeSyntaxFile(TARGET_PATH);
assertSourceIncludesFile(TARGET_PATH, [
  "DEPLOY_PUBLIC_VERIFY_ATTEMPTS",
  "DEPLOY_APP_IMAGE",
  "DEPLOY_EMERGENCY_SOURCE_BUILD",
  "DEPLOY_STORE_BACKEND",
  "DEPLOY_SQLITE_PATH",
  "DEPLOY_STORE_CANARY_CHAT_IDS",
  "deploy mode=image",
  "deploy mode=emergency_source_build",
  "remote registry login",
  "image availability: ready",
  "image availability: public anonymous pull confirmed",
  "image availability timed out; falling back to emergency_source_build",
  "app image was not published to registry in time",
  "--image-wait-attempts <n>",
  "--image-wait-delay-ms <ms>",
  "--image-wait-timeout-ms <ms>",
  "--no-image-wait-fallback",
  "remote: compose pull",
  "remote: clear cached",
  "anonymous pull",
  "--deploy-sha",
  "--store-backend <file|canary|sqlite>",
  "--sqlite-path </app/data/signalbrief.sqlite>",
  "--store-canary-chat-ids",
  "archive-sha",
  "legacy alias for --deploy-sha",
  "--emergency-source-build",
  "pack source commit=",
  ".deploy-runtime-store.env",
  "remote: persist store runtime overrides",
  "remote: load store runtime overrides",
  "store runtime overrides persist across deploys until explicitly changed",
  "canary store deploy requires --store-canary-chat-ids",
  "store canary chat IDs require --store-backend canary",
  "expected store_backend=",
  "expected store_sqlite_path=",
  "--force-recreate",
  "production deploy requires a CI-built image or an explicit emergency fallback",
  "app image inferred from git remote",
  "registry deploy requires DEPLOY_REGISTRY_USER and DEPLOY_REGISTRY_PASSWORD together",
  "staging promotion gate",
  "--skip-staging-gate",
  "release window gate",
  "Use --hotfix only for active incidents",
  "remote: runtime verify",
  "scheduler health check failed after retries",
]);
