const INDUSTRY_TOPICS = [
  "HEALTHCARE",
  "FINANCIAL SERVICES",
  "PE×M&A",
  "ENERGY",
  "CONSUMER",
  "LIFE SCIENCES",
  "TECHNOLOGY",
  "INDUSTRIALS",
  "REAL ESTATE",
  "PUBLIC SECTOR",
];

const CAPABILITY_TOPICS = [
  "AI×TECH",
  "STRATEGY",
  "POLICY×REGULATORY",
  "SUSTAINABILITY",
  "DIGITAL",
  "M&A ADVISORY",
  "TALENT",
];

const DEFAULT_TOPICS = [...INDUSTRY_TOPICS, ...CAPABILITY_TOPICS];

module.exports = {
  INDUSTRY_TOPICS,
  CAPABILITY_TOPICS,
  DEFAULT_TOPICS,
};
