const INDUSTRY_TOPICS = [
  "HEALTHCARE",
  "LIFE SCIENCES",
  "TECHNOLOGY",
  "ENERGY",
  "FINANCIAL SERVICES",
  "CONSUMER & RETAIL",
  "INDUSTRIALS",
];

const DEFAULT_TOPICS = [...INDUSTRY_TOPICS];

module.exports = {
  INDUSTRY_TOPICS,
  DEFAULT_TOPICS,
};
